{{- range $namespace, $metadata := .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  {{- if $metadata.labels }}
  labels:
  {{- toYaml $metadata.labels | nindent 4 }}
  {{- end }}
  {{- if $metadata.annotations }}
  annotations:
  {{- toYaml $metadata.annotations | nindent 4 }}
  {{- end }}
{{- end }}
