---
apiVersion: v1
kind: Service
metadata:
  name: healthchecks
  labels:
    app: healthchecks
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: healthchecks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthchecks
  labels:
    app: healthchecks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthchecks
  template:
    metadata:
      labels:
        app: healthchecks
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: healthchecks
          lifecycle:
            postStart:
              exec:
                command:
                - touch
                - /tmp/healthy
          httpGet:
            path: /index.html
            port: 80
            host: localhost
            scheme: HTTP
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 25
            timeoutSeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 12
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 6
          image: bitnami/apache:2.4
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop: ["ALL"]
