{{- range $cat, $catval := $.Values.catalogs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-29"
    argocd.argoproj.io/hook: PreSync
  name: oc-mirror-{{ $cat }}
  namespace: {{ $.Values.namespace }}
spec:
  ttlSecondsAfterFinished: null
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: container
        image: {{ $.Values.jobImage }}
        env:
          - name: HTTP_PROXY
            value: {{ $.Values.httpProxy }}
          - name: HTTPS_PROXY
            value: {{ $.Values.httpsProxy }}
          - name: NO_PROXY
            value: {{ $.Values.noProxy }}
          - name: DOCKER_CONFIG
            value: /tmp/docker/
        command:
          - "/bin/sh"
          - "-c"
          - |
            cd /tmp
            # Check if catalog exists
            if skopeo inspect --tls-verify=false docker://{{ $.Values.privateRegistry }}/redhat/{{ $cat }}:{{ $.Values.version}}; then
            echo "info: The catalog {{ $cat }} has already been mirrored, nothing to do"
            else
            # Download oc-mirror plugin
            curl -O {{ $.Values.ocMirror }}
            tar xvzf oc-mirror.tar.gz
            chmod +x oc-mirror
            # Run the mirroring process
            ./oc-mirror --config=/tmp/config/imagesetconfiguration.yaml docker://{{ $.Values.privateRegistry }} --dest-skip-tls=true
            # Tag the index image
            skopeo copy docker://{{ $.Values.privateRegistry }}/redhat/{{ $catval.catalog }}:{{ $.Values.version }} docker://{{ $.Values.privateRegistry }}/redhat/{{ $cat }}:{{ $.Values.version}} --src-tls-verify=false --dest-tls-verify=false
            fi
        volumeMounts:
        - name: imageset-config
          mountPath: /tmp/config
        - name: docker-config
          mountPath: /tmp/docker/
      restartPolicy: Never
      volumes:
      - name: imageset-config
        configMap:
          name: oc-mirror-{{ $cat }}
      - name: docker-config
        secret:
          secretName: pull-secret
{{- end }}
