{{- range $cat, $catval := $.Values.catalogs }}
{{- range $pac, $pacval := $catval.packages }}
{{- if ne $pacval.namespace "openshift-operators" }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-26"
  name: {{ $pacval.namespace }}
  labels:
    name: {{ $pacval.namespace }}
{{- end }}
{{- end }}
{{- end }}
