{{- range $cat, $catval := $.Values.catalogs }}
{{- range $pac, $pacval := $catval.packages }}
{{- if ne $pacval.namespace "openshift-operators" }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
  name: {{ $pacval.namespace }}
  namespace: {{ $pacval.namespace }}
{{- end }}
{{- end }}
{{- end }}
