---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  password: {{ password123 | b64enc }}
type: Opaque
