# General
version: v4.14
namespace: oc-mirror
catalogNamespace: openshift-marketplace

# Job
jobImage: registry.redhat.io/ubi9/skopeo:9.3-5
ocMirror: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/oc-mirror.tar.gz

# Registries
redhatRegistry: registry.redhat.io/redhat
privateRegistry: registry-quay-quay.apps.gitops.sandbox1568.opentlc.com/operators/v4.14

# Proxy
httpProxy: ""
httpsProxy: ""
noProxy: ""

# Custom catalogs
catalogs:

  # servicemesh-v2-2-3:
  #   catalog: redhat-operator-index
  #   packages:
  #     servicemeshoperator:
  #       namespace: openshift-operators
  #       channel: stable
  #       version: 2.2.3-0
  #     kiali-ossm:
  #       namespace: openshift-operators
  #       channel: stable
  #       version: 1.57.7
  #     jaeger-product:
  #       namespace: openshift-operators
  #       channel: stable
  #       version: 1.34.1-5

  servicemesh-v2-4-4:
    catalog: redhat-operator-index
    packages:
      servicemeshoperator:
        namespace: openshift-operators
        channel: stable
        version: 2.4.4-0
      kiali-ossm:
        namespace: openshift-operators
        channel: stable
        version: 1.65.10
      jaeger-product:
        namespace: openshift-operators
        channel: stable
        version: 1.47.1-5

  oadp-v1-3-0:
    catalog: redhat-operator-index
    packages:
      redhat-oadp-operator:
        namespace: openshift-operators
        channel: stable-1.3
        version: 1.3.0
